services:
    geoffgarit.csv-bundle.parse:
        class: src/Command/ParseCsvCommand
        public: true
        autowire: true
        tags:
            -  { name: console.command, command: 'geoffgarit:csv-bundle:parse' }
